### ISSUE TITLE
Shoshin port meta issue

### ISSUE THREAD

**Issue by mconcat** [topology-gg/shoshin-cairo-1#6]
Tasks left to port the existing code of [Shoshin](https://github.com/topology-gg/shoshin):

- [ ] Dynamics.cairo for compute movement for characters
- [ ] Physics.cairo for collision detection and hitbox logic
- [ ] Engine.cairo for perception-body-physics loop
- [ ] Bodies(Antoc and Jessica) port
- [ ] Misc. including perceptible, combo, etc
